### ISSUE TITLE
Who site moved

### ISSUE THREAD

**Issue by ruzsaz** [sarrabenyahia/webscrap_health_monitoring#1]
The site is moved from "https://www.whocc.no/atc_ddd_index" to "https://atcddd.fhi.no/atc_ddd_index", so the code drops
```
...
File "/home/ruzsaz/ttt/webscrap_health_monitoring/bs4/whocc.py", line 118, in async_response_parsed
    runtime_element = parsed.select_one("#last_updated").previous_sibling
AttributeError: 'NoneType' object has no attribute 'previous_sibling'
```

To reflect the changes update the file /bs4/whocc.py, line 14.

Anyway, good work & many thanks sarrabenyahia!

**Comment by sarrabenyahia** [comment]
Thank for the notification ! Could you create a pull request to correct the issue ?

**Comment by ruzsaz** [comment]
Sure, but this is my first PR, so be gentle! (they say the first will be remembered forever...)
